/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EnviarArtigoRouteImport } from './routes/enviar-artigo'
import { Route as CoppaRouteImport } from './routes/coppa'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarArtigoRoute = EnviarArtigoRouteImport.update({
  id: '/enviar-artigo',
  path: '/enviar-artigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoppaRoute = CoppaRouteImport.update({
  id: '/coppa',
  path: '/coppa',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artigos': typeof ArtigosRoute
  '/coppa': typeof CoppaRoute
  '/enviar-artigo': typeof EnviarArtigoRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artigos': typeof ArtigosRoute
  '/coppa': typeof CoppaRoute
  '/enviar-artigo': typeof EnviarArtigoRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artigos': typeof ArtigosRoute
  '/coppa': typeof CoppaRoute
  '/enviar-artigo': typeof EnviarArtigoRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artigos'
    | '/coppa'
    | '/enviar-artigo'
    | '/eventos'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/artigos'
    | '/coppa'
    | '/enviar-artigo'
    | '/eventos'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artigos'
    | '/coppa'
    | '/enviar-artigo'
    | '/eventos'
    | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArtigosRoute: typeof ArtigosRoute
  CoppaRoute: typeof CoppaRoute
  EnviarArtigoRoute: typeof EnviarArtigoRoute
  EventosRoute: typeof EventosRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar-artigo': {
      id: '/enviar-artigo'
      path: '/enviar-artigo'
      fullPath: '/enviar-artigo'
      preLoaderRoute: typeof EnviarArtigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coppa': {
      id: '/coppa'
      path: '/coppa'
      fullPath: '/coppa'
      preLoaderRoute: typeof CoppaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArtigosRoute: ArtigosRoute,
  CoppaRoute: CoppaRoute,
  EnviarArtigoRoute: EnviarArtigoRoute,
  EventosRoute: EventosRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
